services:
  skillshare.api:
    image: skillshare.api
    container_name: skillshare-api
    build:
      context: .
      dockerfile: SkillShare.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - RabbitMQSettings__HostName=rabbitmq 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=skillshare.db;Port=5432;Database=SkillShare;Username=postgres;Password=postgres
      - ConnectionStrings__RabbitMQ=amqp://admin:admin@rabbitmq:5672/
      - RedisSettings__Url=redis:6379
      - RedisSettings__InstanceName=local
    depends_on:
      - skillshare.db
      - rabbitmq
      - redis
    restart: unless-stopped
    networks:
      - mynw

  skillshare.db:
    image: postgres:17
    container_name: skillshare-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SkillShare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynw

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: skillshare-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    depends_on:
      - skillshare.db
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynw

  rabbitmq: 
    image: rabbitmq:3-management 
    container_name: skillshare-rabbitmq 
    restart: always 
    environment:
      - RABBITMQ_DEFAULT_USER=admin       
      - RABBITMQ_DEFAULT_PASS=admin     
    ports:
      - "5672:5672"    
      - "15672:15672"  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - mynw

  redis:
    image: redis:alpine
    container_name: skillshare-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - mynw
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  prometheus:
    image: prom/prometheus
    container_name: skillshare-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - mynw
    
  grafana:
    image: grafana/grafana
    container_name: skillshare-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw

volumes:
  postgres_data:
    name: skillshare_postgres_data
  pgadmin_data:
    name: skillshare_pgadmin_data
  rabbitmq_data: 
    name: skillshare_rabbitmq_data
  redis_data:
    name: skillshare_redis_data
  prometheus_data:
    name: skillshare_prometheus_data
  grafana_data:
    name: skillshare_grafana_data

networks:
  mynw:
    name: skillshare_network
    driver: bridge